version: '3.4'

services:
  db:
    container_name: MSSQL
    image: "mcr.microsoft.com/mssql/server:2019-latest"

  gb.aspnet.webstore:
    image: ${DOCKER_REGISTRY-}gbaspnetwebstore
    build:
      context: .
      dockerfile: GB.ASPNET.WebStore/Dockerfile
